version: "3.7"

services:
  db:
    image: postgres
    restart: on-failure
    container_name: db
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - custom

  app:
    build:
      context: .
    environment:
      - sqlalchemy.url=postgresql+asyncpg://db
    env_file:
      - .env
    container_name: app
    command: ["/bass_to_bass/docker/app.sh"]
    restart: always
    ports:
      - 9999:8000
    depends_on:
      - db
    networks:
      - custom

  nginx:
    container_name: web
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - custom

networks:
  custom:
    driver: bridge