version: "3.7"

services:
  db:
    image: postgres
    restart: on-failure
    container_name: db_bass_to_bass
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: bass_to_bass
    command: ["/bass_to_bass/docker/app.sh"]
    restart: always
    ports:
      - 9999:8000
    depends_on:
      - db